### PR TITLE
Fix analog sticks not reported to libretro interface

### PR DESCRIPTION
**Pull request by garbear**
Use of analog device is at:

https://github.com/libretro/fbalpha/blob/c0e0632/src/burner/libretro/libretro.cpp#L1941

### CODE REVIEW

**Comment by barbudreadmon** [comment]
@garbear The current code works perfectly fine in retroarch (analog controls reported in "quick menu > controls" + they work as expected when playing). 

If lakka behave differently than retroarch about this, then this is surely a lakka issue.

I want @fr500 and @twinaphex opinion on this before merging it.

**Comment by fr500** [comment]
This is probably about kodi's retroplayer.
He's right, seems his player is more compliant than ours :P

**Comment by barbudreadmon** [comment]
Ok then, i hope no issue will appear from this change.

**Comment by fr500** [comment]
Shouldn't cause any issues

**Comment by garbear** [comment]
Thanks for merging. I build a project around libretro input called the Controller Topology Project. It's a database of controller data that Kodi uses for zero-config input. We also rely on libretro input data, and noncompliances breaks the autoconfig process.

**Pull request merged**
