### PR TITLE
Create standard C fallback for endian swapping

### PR DESCRIPTION
**Pull request by ensra**

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Some information would be appreciated, what device needs this ?

**Comment by ensra** [comment]
Not really a device, but the bulk build for libretro-fbalpha was failing on NetBSD/powerpc.

**Comment by barbudreadmon** [comment]
ok, so powerpc, perhaps the same defines as HW_RVL (wii/wiiU iirc, which are ppc devices) would be better then ? Seems to me like asm stuff should be faster.

**Comment by barbudreadmon** [comment]
Anyway i'll merge it for now, let me know if you feels like testing for better optimization.

**Pull request merged**
