### PR TITLE
Master

### PR DESCRIPTION
**Pull request by RetroUp**

### CODE REVIEW

**Comment by twinaphex** [comment]
@barbudreadmon You want to review this? I'll leave it in your hands.

**Comment by RetroUp** [comment]
I didn't mean for that 4th commit to be merged. Just the first 3.

**Comment by RetroUp** [comment]
I'm new to github. The correct way for me to keep the 4th commit out of the pull request would have been for me to create a new branch for it?

**Comment by barbudreadmon** [comment]
I can't merge this, it would break build on any non-windows system. Also i don't like how you dealt with coleco, there is no need to change szinfo/szname in d_coleco.cpp.
I'll try to fix things using your ideas.

**Comment by RetroUp** [comment]
I only tested on windows so I'll trust you that it breaks non-win but I modeled the 7z support after libretro_mame and fba upstream which made me assume it would cross compile.

I changed szinfo so the menu would show "P1" and "P2". Using 2 controllers per player was confusing without some notation in the menu.

My plan is to remove everything except coleco from FBA to make a dedicated coleco core.

And sorry about the accidental hashtag comment references.

**Comment by barbudreadmon** [comment]
I'll check how libretro_mame deal with 7z. What i'm sure after spending an hour trying to fix this : the lib7z library in fba is not cross-platform at all.

**Comment by barbudreadmon** [comment]
Did you own a coleco ? I heard 2,4,6,8 buttons were actually a second d-pad and 5,7,9,0 a third d-pad, is that true for all games ? If it is, we should probably map those to the analog sticks, and map the 6 remaining to actual buttons (# as start, * as select, the last 4 as A/B/X/Y). I asked about this a few months back in the issue about inputs but nobody was able or willing to answer.

**Comment by barbudreadmon** [comment]
I was pessimistic, it seems i was able to solve the issue with lib7z, could you confirm things work on windows too with my latest commit ?

**Comment by RetroUp** [comment]
In nearly every game they are simply a numpad used to select skill/players. A few games used an overlay to reassign them. https://archive.org/details/colecovisionoverlays

Only one game used 2,4,6,8 as a second d-pad. There was never a 3rd.

Best to think of it as a simple numpad when trying to create a layout. Using the analog sticks is a good solution to keep them all on one controller. I didn't know how to access the analogs.

Thanks. I will test 7z on Win tomorrow. FBA's 7z  is based on mame 0.145 - 2012.

**Comment by barbudreadmon** [comment]
I'll close this PR and think about a solution for coleco.
Open an issue if 7z don't work on windows/xbox.

**Comment by RetroUp** [comment]
7z works. Thanks.

For coleco, I don't think there is a perfect way to do it. The best is probably something sequential. As close to a numpad as possible.

B=Fire 1
X=Fire 2
Y=1
X=2
L1=3
R1=4
L2=5
R2=6
Analogs=7,8,9,0
Select=*
Start=#

**Pull request closed without merging**
