### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by barbudreadmon**

### CODE REVIEW

**Comment by erdem4life** [comment]
Hello barbudreadmon. 
Aero fighters special taiwan rom update pleasee. And supported turkish language.

**Comment by barbudreadmon** [comment]
@erdem4life i don't understand

**Comment by erdem4life** [comment]
Aero fighters special/ sonig wing lımıted taiwan japan rom adding. Please

**Comment by barbudreadmon** [comment]
@erdem4life ok, now i understand, you are asking for ZN1 support : 
1. It's not happening, most likely **never** because this is 3D hardware
2. We are not taking request
3. Even if we were taking request, posting this in a random PR is just wrong

About turkish language support, i don't understand either, not that i care...

**Comment by erdem4life** [comment]
Mame It works smoothly realy..

**Comment by erdem4life** [comment]
Do you have a project zn1.??

**Pull request merged**
