### PR TITLE
map whole memory area for CPS1,2 instead of just one segment 

### PR DESCRIPTION
**Pull request by RetroSven**
used for cheat code searching

https://github.com/libretro/RetroArch/issues/7212#issuecomment-423780460

### CODE REVIEW

**Comment by barbudreadmon** [comment]
That won't do, you are enlarging savestates with duplicate data + breaking support for previous savestates + diverging from standalone code. There is no way i can merge this.

**Comment by RetroSven** [comment]
oh I didn't see those methods were also being used for save states - will adjust

**Comment by barbudreadmon** [comment]
@RetroSven what part of the ram are you trying to include exactly ?

**Comment by RetroSven** [comment]
@barbudreadmon isn't it possible for one of the other cps memory segments to contain useful game data?  I see CpsRam90, CpsRamFF (the default), CpsReg, CpsZRamC0, CpsZRamF0, CpsRam708, CpsFrg, and CpsRam660.

**Comment by barbudreadmon** [comment]
@RetroSven 
CpsRam90 is video ram (not needed ?)
CpsReg/CpsFrg are registers (not needed ?)
CpsZRamC0/CpsZRamF0 are sound ram (not needed ?)

I have some doubts about CpsRam660/CpsRam708, i think one of them is related to some obscure pachinko game, and the other is related to the communication board for wiring 2 cabinets.

Is there any evidence of adding any of those segments improving cheat search ?

**Comment by RetroSven** [comment]
@barbudreadmon yeah I jumped the gun on that one - please look at the most recent commit - the problem wasn't that some memory was missing - it's that it wasn't even being detected at all for certain games

**Comment by barbudreadmon** [comment]
Yeah, as i mentioned in https://github.com/libretro/fbalpha/issues/236 too. Feel free to add support for more system as long as it doesn't involve changes in the vanilla code (we will try to figure out a way to make it "clean" if it comes to this)

**Pull request merged**
